package queries

const SqliteGetDockerNamespaceID = "SELECT ID FROM DOCKER_NAMESPACE WHERE NAMESPACE_NAME = ?"
const SqliteGetDockerRepositoryID = "SELECT ID FROM DOCKER_REPOSITORY WHERE ID = ? AND DOCKER_REPOSITORY_NAME = ?"
const SqliteCreateDockerNamespace = "INSERT INTO DOCKER_NAMESPACE(NAMESPACE_NAME) VALUES(?) RETURNING ID"
const SqliteCreateDockerRepository = "INSERT INTO DOCKER_REPOSITORY(DOCKER_REPOSITORY_NAME, NAMESPACE_ID) VALUES(?, ?)"