CREATE TABLE IF NOT EXISTS DOCKER_NAMESPACE(
	ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))),
	NAMESPACE_NAME TEXT UNIQUE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE IF NOT EXISTS DOCKER_REPOSITORY(
	ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))),
	DOCKER_REPOSITORY_NAME TEXT NOT NULL,
	DOCKER_REPOSITORY_DESCRIPTION TEXT,
	NAMESPACE_ID TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (NAMESPACE_ID) REFERENCES DOCKER_NAMESPACE(ID),
	UNIQUE (NAMESPACE_ID, DOCKER_REPOSITORY_NAME)
);

CREATE TABLE IF NOT EXISTS DOCKER_BLOB_UPLOAD_SESSION(
	SESSION_ID TEXT PRIMARY KEY,
	BLOB_DIGEST TEXT NOT NULL UNIQUE,
	LASTUPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IS_CHUNKED INTEGER -- 0 - MONOLITHIC 1 - CHUNKED 
);

-- LAYER AND IMAGE CONFIG WILL BE STORED IN THIS TABLE WITH STORAGE LOCATION
CREATE TABLE IF NOT EXISTS DOCKER_IMAGE_BLOB_META (
  DIGEST TEXT PRIMARY KEY,
  SIZE INTEGER NOT NULL,
	STORAGE_LOCATION TEXT NOT NULL UNIQUE,
	MEDIA_TYPE TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LASTUPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE IF NOT EXISTS DOCKER_IMAGE_TAG(
	ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))),
	TAG TEXT NOT NULL,
	DOCKER_REPO_ID TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (DOCKER_REPO_ID) REFERENCES DOCKER_REPOSITORY(ID),
	UNIQUE (TAG, DOCKER_REPO_ID)
);

CREATE TABLE IF NOT EXISTS DOCKER_IMAGE_PLATFORM_CONFIG(
	ID TEXT PRIMARY KEY, -- digest of docker image config
	DOCKER_REPO_ID TEXT NOT NULL,
	TAG_ID TEXT NOT NULL, 
	OS TEXT NOT NULL,
	ARCH TEXT NOT NULL,
	PROPERTIES TEXT, -- JSON OBJECT OF PROPERTIES
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	FOREIGN KEY (DOCKER_REPO_ID) REFERENCES DOCKER_REPOSITORY(ID),
	UNIQUE (TAG_ID, OS, ARCH)
);

CREATE TABLE IF NOT EXISTS DOCKER_LAYER_TAG_MAPPING(
	MAPPING_ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))),
	IMAGE_TAG_ID TEXT NOT NULL,
	IMAGE_CONFIG_DIGEST TEXT NOT NULL,
	LAYER_DIGEST TEXT NOT NULL,
	LAYER_INDEX INTEGER NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	FOREIGN KEY (IMAGE_TAG_ID) REFERENCES DOCKER_IMAGE_TAG(ID),
	FOREIGN KEY (LAYER_DIGEST) REFERENCES DOCKER_IMAGE_BLOB_META(DIGEST) ON DELETE CASCADE,
	UNIQUE (IMAGE_CONFIG_DIGEST , IMAGE_TAG_ID , LAYER_DIGEST, LAYER_INDEX)
);

CREATE TABLE IF NOT EXISTS DOCKER_IMAGE_MANIFEST(
	ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))), 
	DIGEST TEXT NOT NULL UNIQUE,
	SIZE INTEGER NOT NULL,
	MEDIA_TYPE TEXT NOT NULL,
	MANIFEST_CONTENT TEXT NOT NULL,
	IMAGE_TAG_ID TEXT NOT NULL,
	IMAGE_CONFIG_DIGEST TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	FOREIGN KEY (IMAGE_TAG_ID) REFERENCES DOCKER_IMAGE_TAG(ID),
	UNIQUE(IMAGE_TAG_ID, IMAGE_CONFIG_DIGEST)
);